require 'bowndler'

module Bowndler
  module Commands
    class Autohook
      HOOK = <<-HOOK

# BEGIN Autogenerated by bowndler, do not edit
require "bowndler"
Bowndler.hook
# END Autogenerated by bowndler
HOOK

      attr_reader :gemfile

      def initialize(gemfile)
        @gemfile = gemfile
      end

      def call
        File.open(gemfile, 'a+') do |f|
          contents = f.read
          f << HOOK unless contents.include?(HOOK)
        end
      end

    end
  end
end
